# Generated by Django 5.0.2 on 2024-03-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.URLField(verbose_name='Изображение'),
        ),
    ]
