# Generated by Django 5.0.2 on 2024-03-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
