# Generated by Django 5.0.2 on 2024-03-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='world_premiere',
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='actors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='Постер'),
        ),
    ]
